# Generated by Django 5.1.5 on 2025-03-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsms', '0002_remove_product_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Billing_Employee', 'Billing Employee')], max_length=20),
        ),
    ]
