# Generated by Django 5.1.5 on 2025-03-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsms', '0003_userlogin_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Billing_Employee', 'Billing Employee')], default='Admin', max_length=20),
        ),
    ]
