# Generated by Django 5.1.5 on 2025-03-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsms', '0007_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gsms.supplier'),
        ),
    ]
