# Generated by Django 5.1.5 on 2025-03-27 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsms', '0009_alter_transaction_pay_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
